# k8s/aggregator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: aggregator-service:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator-service
  ports:
    - port: 8080
      targetPort: 8080