server:
  port: 8080

spring:
  grpc:
    client:
      channel:
        servicea:
          target: "service-a:9091" # either using dns prefix or not, both are valid

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

serviceA:
  uri: 'http://service-a:8081/api/slow-data/'