server:
  port: 8082 # REST HTTP/1.1 Port

spring:
  threads:
    virtual:
      enabled: true # Enable Spring Boot 4 Virtual Threads
  grpc:
    server:
      port: 9092 # gRPC HTTP/2 Port

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics