server:
  port: 8081 # REST HTTP/1.1 Port

spring:
  threads:
    virtual:
      enabled: true # Enable Spring Boot 4 Virtual Threads
  grpc:
    server:
      port: 9091 # gRPC HTTP/2 Port

  autoconfigure:
    exclude:
      - org.springframework.boot.grpc.server.autoconfigure.security.GrpcServerOAuth2ResourceServerAutoConfiguration

  management:
    tracing:
      sampling:
        probability: 1.0 # Sample 100% of requests for benchmarking

  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,traces

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"